name : datetime
on: 
  schedule:
        - cron : '*/15 * * * *'
jobs :
  print-date:
      runs-on : ubuntu-latest
      steps : 
         - name: date and time 
           run : |
             echo "date and time ($date)"
  
    

    
     
  
