name: Date and Time

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  print-DateTime:
    runs-on: ubuntu-latest
    steps:
      - name: Print current date and time
        run: |
          echo "Current date and time: $(date)"
 
